document.querySelectorAll('[data-demo-email]').forEach(function(button){button.addEventListener('click',function(){document.querySelector('input[name="email"]').value=button.dataset.demoEmail;document.querySelector('input[name="password"]').value=button.dataset.demoPassword;});});

document.querySelectorAll('.tabs').forEach(function(group){group.addEventListener('click',function(e){var btn=e.target.closest('.tab'); if(!btn) return; group.querySelectorAll('.tab').forEach(function(t){t.classList.remove('active')}); btn.classList.add('active'); var tab=btn.dataset.tab; if(!tab) return; document.querySelectorAll('.tab-panel').forEach(function(panel){panel.classList.add('hidden')}); document.querySelectorAll('.tab-panel.'+tab).forEach(function(panel){panel.classList.remove('hidden')}); document.querySelectorAll('[data-status]').forEach(function(card){card.style.display=(tab==='all'||card.dataset.status===tab)?'grid':'none'});});});

var search=document.getElementById('studentSearch'); if(search){search.addEventListener('input',function(){var q=search.value.toLowerCase(); document.querySelectorAll('[data-student-card]').forEach(function(card){card.style.display=card.dataset.name.includes(q)?'block':'none'});});}

var modal=document.getElementById('evalModal'); function updateScore(){if(!modal)return; var values=[].map.call(modal.querySelectorAll('[data-score]'),function(r){r.previousElementSibling.textContent=r.value; return Number(r.value)}); var avg=values.reduce(function(a,b){return a+b},0)/values.length; document.getElementById('finalScore').textContent=avg.toFixed(1);} document.querySelectorAll('[data-score]').forEach(function(r){r.addEventListener('input',updateScore)}); document.querySelectorAll('.js-evaluate').forEach(function(btn){btn.addEventListener('click',function(){document.getElementById('modalSetTitle').textContent=btn.dataset.title; document.getElementById('modalStudent').textContent=btn.dataset.student; document.getElementById('modalGenre').textContent=btn.dataset.genre; document.getElementById('modalDuration').textContent=btn.dataset.duration; document.getElementById('modalListen').href=btn.dataset.url; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); updateScore();});}); document.querySelectorAll('[data-close-modal]').forEach(function(btn){btn.addEventListener('click',function(){modal.classList.remove('open'); modal.setAttribute('aria-hidden','true');});}); if(modal){modal.addEventListener('click',function(e){if(e.target===modal){modal.classList.remove('open'); modal.setAttribute('aria-hidden','true');}});}
function applyInitialTabs(){document.querySelectorAll('.tabs .tab.active[data-tab]').forEach(function(btn){var tab=btn.dataset.tab;document.querySelectorAll('.tab-panel').forEach(function(panel){panel.classList.add('hidden')});document.querySelectorAll('.tab-panel.'+tab).forEach(function(panel){panel.classList.remove('hidden')});document.querySelectorAll('[data-status]').forEach(function(card){card.style.display=(tab==='all'||card.dataset.status===tab)?'grid':'none'});});}
applyInitialTabs();
